### PR TITLE
ci: Run README examples

### PR DESCRIPTION
**Pull request by danielabrozzoni**
Adds a "doctest" feature useful if you want to run the README.md tests.
Largely copied from bdk's CI workflow.

### CODE REVIEW

**Comment by danielabrozzoni** [comment]
self-ACK 6967e0474814285cfe9aa1ff59323590ceeadf23

**Review by wszdexdrf — APPROVED** [review]
ACK 6967e0474814285cfe9aa1ff59323590ceeadf23

**Review by afilini — APPROVED** [review]
ACK 6967e0474814285cfe9aa1ff59323590ceeadf23

**Comment by danielabrozzoni** [comment]
Oops, an unrelated README change slipped in

self-ACK  255bffb

**Pull request merged**
