### PR TITLE
Add a new Signer for BDK

### PR DESCRIPTION
**Pull request by wszdexdrf**
The test for the Signer is mostly the BDK example (with small changes) available on the [bdk doc homepage](https://docs.rs/bdk/0.20.0/bdk/).

### CODE REVIEW

**Comment by wszdexdrf** [comment]
The trezor emulator is failing because it has no coins. It is initialized with slip0014 (well-defined, documented way) hence people are quickly stealing the coins :D

**Comment by danielabrozzoni** [comment]
The implementation seems correct, but architecturally I'd go with the other way around: instead of making bdk a dependency of rust-hwi, why not making rust-hwi a dependency on bdk? We could have a feature on bdk called "hwi" which includes the rust-hwi crate and exposes the HardwareWalletSigner

**Comment by danielabrozzoni** [comment]
> The trezor emulator is failing because it has no coins. It is initialized with slip0014 (well-defined, documented way) hence people are quickly stealing the coins :D

When moving this to the bdk repo you can use the bdk utils for tests, which doesn't involve moving coins, just modifying the bdk database (or start bitcoind in regtest for the functional tests)

**Comment by wszdexdrf** [comment]
Moved to https://github.com/bitcoindevkit/bdk/pull/682

**Pull request closed without merging**
