### PR TITLE
Bump version to 0.10.0

### PR DESCRIPTION
**Pull request by notmandatory**

### CODE REVIEW

**Comment by notmandatory** [comment]
@oleonardolima please confirm this is all we need for the release.

**Comment by oleonardolima** [comment]
> @oleonardolima please confirm this is all we need for the release.

Yes, I think it's all we need.

**Review by oleonardolima — COMMENTED** [review]
utACK 3e0efe1957fe4370f9620cbed6f857826ed38cd4

**Comment by notmandatory** [comment]
release also published https://crates.io/crates/hwi

https://github.com/bitcoindevkit/rust-hwi/releases/tag/v0.10.0

**Pull request merged**
