### PR TITLE
Upgrade bitcoin

### PR DESCRIPTION
**Pull request by tcharding**
Upgrade 
- bitcoin to v0.31.0
- miniscript v11.0.0

### CODE REVIEW

**Comment by tcharding** [comment]
I think the CI fail is unrelated to this PR, am I wrong?

**Comment by danielabrozzoni** [comment]
> I think the CI fail is unrelated to this PR, am I wrong?


Yep, I'll try to look into it these days, thanks!

**Comment by tcharding** [comment]
No changes, just seeing if CI is working.

**Comment by danielabrozzoni** [comment]
Thanks! Can you try rebasing on master? CI should be fixed now :)

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by danielabrozzoni — APPROVED** [review]
Sorry this took so long,

ACK 943b6c103bc44a8ac4134f1ad0f6e4a493796beb

**Pull request merged**
